baseURL = 'https://info.steamhunter.link/'
locale = 'zh-cn'
title = 'Steam 蒸汽猎手 | 游戏情报站'
theme = ''
defaultContentLanguage = 'zh-cn'
hasCJKLanguage = true
paginate = 10

[params]
  author = 'SteamHunter'
  description = '每日精选 Steam 游戏特惠、喜加一福利与版本补丁深度解析'
  keywords = ['Steam', '游戏资讯', '喜加一', '限免', '史低折扣', '版本补丁']
  repoURL = 'https://github.com/keirosang'
  subtitle = '每日精选 Steam 游戏特惠、喜加一福利与版本补丁深度解析'
  tgChannel = 'https://t.me/steamhunterlink'

[menu]
  [[menu.main]]
    name = '首页'
    url = '/'
    weight = 1
  [[menu.main]]
    name = '限免福利'
    url = '/categories/限免福利/'
    weight = 2
  [[menu.main]]
    name = '特惠折扣'
    url = '/categories/特惠折扣/'
    weight = 3
  [[menu.main]]
    name = '游戏资讯'
    url = '/categories/游戏资讯/'
    weight = 4
  [[menu.main]]
    name = '标签云'
    url = '/tags/'
    weight = 5
  [[menu.main]]
    name = '关于本站'
    url = '/about/'
    weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'monokailight'
    lineNos = false
